"""Framework-specific invocation adapters for the universal test runner.

The scheduler, store, and privileged runtime consume only normalized attempt
descriptors. This module is the sole place that translates a driver into
framework CLI/reporter details.
"""

from __future__ import annotations

import os
from pathlib import Path

from .universal_test_runtime import TestAttemptDescriptor


_PYTEST_SHARD_PLUGIN = b'''"""Trusted deterministic pytest partitioner generated by DevCoordinator."""
import hashlib
import os


def pytest_collection_modifyitems(config, items):
    index = int(os.environ["DEVCOORDINATOR_TEST_SHARD_INDEX"])
    count = int(os.environ["DEVCOORDINATOR_TEST_SHARD_COUNT"])
    selected = []
    deselected = []
    for item in items:
        identity = hashlib.sha256(item.nodeid.encode("utf-8")).digest()
        (selected if int.from_bytes(identity[:8], "big") % count == index else deselected).append(item)
    if deselected:
        config.hook.pytest_deselected(items=deselected)
    items[:] = selected
'''


def _write_all(descriptor: int, payload: bytes) -> None:
    offset = 0
    while offset < len(payload):
        written = os.write(descriptor, payload[offset:])
        if written <= 0:
            raise OSError("driver adapter write made no progress")
        offset += written


def _publish_pytest_shard_plugin(output: Path) -> Path:
    path = output / "devcoordinator_pytest_shard.py"
    path.unlink(missing_ok=True)
    descriptor = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        _write_all(descriptor, _PYTEST_SHARD_PLUGIN)
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    return path


def is_dotnet_project_invocation(descriptor: TestAttemptDescriptor) -> bool:
    return (
        len(descriptor.argv) >= 2
        and (
            descriptor.driver == "dotnet"
            or Path(descriptor.argv[0]).name == "dotnet"
        )
        and descriptor.argv[1] in {"build", "test"}
    )


def dotnet_locked_restore_required(descriptor: TestAttemptDescriptor) -> bool:
    return descriptor.source_mode == "immutable" and any(
        binding.get("kind") == "dotnet-packages"
        for binding in descriptor.dependency_bindings
    )


def adapt_driver_invocation(
    descriptor: TestAttemptDescriptor, output: Path
) -> tuple[tuple[str, ...], dict[str, str], Path, str]:
    """Return one fixed no-shell reporter adapter for the typed driver."""

    environment = dict(descriptor.environment)
    environment.update(
        {
            "DEVCOORDINATOR_TEST_SHARD_INDEX": str(descriptor.shard_index),
            "DEVCOORDINATOR_TEST_SHARD_COUNT": str(descriptor.shard_count),
        }
    )
    argv = tuple(descriptor.argv)
    if is_dotnet_project_invocation(descriptor):
        environment.update(
            {
                "DOTNET_CLI_HOME": str(output / "dotnet-cli-home"),
                "DOTNET_CLI_TELEMETRY_OPTOUT": "1",
                "DOTNET_NOLOGO": "1",
                "DOTNET_SKIP_FIRST_TIME_EXPERIENCE": "1",
                "DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE": "1",
            }
        )
    if descriptor.driver == "pytest":
        reporter = output / "reporter.junit.xml"
        if descriptor.shard_count > 1:
            _publish_pytest_shard_plugin(output)
            inherited_pythonpath = environment.get("PYTHONPATH")
            environment["PYTHONPATH"] = str(output) + (
                ""
                if inherited_pythonpath is None
                else os.pathsep + inherited_pythonpath
            )
            argv += (
                "-p",
                "devcoordinator_pytest_shard",
            )
        argv += ("--junitxml", str(reporter))
        kind = "junit"
    elif descriptor.driver == "dotnet":
        reporter = output / "reporter.trx"
        dotnet_arguments = argv[2:]
        passthrough = (
            dotnet_arguments.index("--")
            if "--" in dotnet_arguments
            else len(dotnet_arguments)
        )
        if (
            dotnet_locked_restore_required(descriptor)
            and "--no-build" in dotnet_arguments[:passthrough]
        ):
            before_passthrough = tuple(
                argument
                for argument in dotnet_arguments[:passthrough]
                if argument != "--no-build"
            )
            dotnet_arguments = (*before_passthrough, *dotnet_arguments[passthrough:])
            argv = (*argv[:2], *dotnet_arguments)
            passthrough = len(before_passthrough)
        trusted_options: tuple[str, ...] = ()
        if (
            dotnet_locked_restore_required(descriptor)
            and "--no-restore" not in dotnet_arguments[:passthrough]
        ):
            trusted_options += ("--no-restore",)
        trusted_options += (
            "--logger",
            "trx;LogFilePrefix=reporter",
            "--results-directory",
            str(output),
        )
        insertion = 2 + passthrough
        argv = (*argv[:insertion], *trusted_options, *argv[insertion:])
        kind = "trx"
    elif descriptor.driver == "node" and any(
        argument == "--test" or argument.startswith("--test=")
        for argument in argv[1:]
    ):
        reporter = output / "reporter.junit.xml"
        node_options = [
            "--test-reporter=junit",
            f"--test-reporter-destination={reporter}",
        ]
        if descriptor.shard_count > 1:
            node_options.append(
                "--test-shard="
                f"{descriptor.shard_index + 1}/{descriptor.shard_count}"
            )
        argv = (argv[0], *node_options, *argv[1:])
        kind = "junit"
    else:
        reporter = output / "reporter.events.jsonl"
        environment["DEVCOORDINATOR_TEST_EVENTS"] = str(reporter)
        environment["DEVCOORDINATOR_TEST_RESULTS"] = str(reporter)
        kind = "jsonl"
    return argv, environment, reporter, kind


__all__ = [
    "adapt_driver_invocation",
    "dotnet_locked_restore_required",
    "is_dotnet_project_invocation",
]
