#!/usr/bin/python3
"""Trusted bounded reporter wrapper for one universal-test target attempt."""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import re
import resource
import shutil
import signal
import stat
import subprocess
import sys
import tarfile
import threading
import time
from typing import Mapping, NamedTuple, Sequence
import uuid
import xml.etree.ElementTree as ET

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from devcoordinator.universal_test_runtime import (  # type: ignore[import-not-found]
    TestAttemptDescriptor,
    _IMMUTABLE_PYTHON_TOOLCHAIN_MOUNT,
    _safe_id,
)
from devcoordinator.universal_test_artifacts import package_directory  # type: ignore[import-not-found]
from devcoordinator.universal_test_store import TestStoreContractError  # type: ignore[import-not-found]


MAX_LAUNCH_BYTES = 256 * 1024
MAX_RESULT_BYTES = 2 * 1024 * 1024
MAX_RESULT_CHUNK_BYTES = 240 * 1024
MAX_RESULT_CHUNKS = 4_096
MAX_CAPTURE_BYTES = 4 * 1024 * 1024
MAX_REPORT_BYTES = 32 * 1024 * 1024
MAX_CASES = 100_000
MAX_FAILURES = 64
MAX_ARTIFACTS = 64
MAX_FAILURE_DIAGNOSTIC_BYTES = 256 * 1024
MAX_FAILURE_DIAGNOSTIC_FILE_BYTES = 64 * 1024
MAX_TOOLCHAIN_BYTES = 1024 * 1024 * 1024
MAX_DOTNET_GLOBAL_JSON_BYTES = 64 * 1024
MAX_DOTNET_READINESS_STREAM_BYTES = 256 * 1024
_DOTNET_NUGET_SOURCE_DESTINATION = ".devcoordinator-dependencies/nuget-source"
_DOTNET_PROJECT_SUFFIXES = {
    ".csproj",
    ".dll",
    ".fsproj",
    ".sln",
    ".slnx",
    ".vbproj",
}
_DOTNET_RESTORE_PROJECT_SUFFIXES = {
    ".csproj",
    ".fsproj",
    ".sln",
    ".slnx",
    ".vbproj",
}
_DOTNET_RESTORE_VALUE_OPTIONS = frozenset(
    {
        "--configuration",
        "-c",
        "--runtime",
        "-r",
        "--framework",
        "-f",
        "--arch",
        "-a",
        "--os",
    }
)
_DOTNET_RESTORE_GRAPH_PROPERTIES = frozenset(
    {
        "configuration",
        "platform",
        "runtimeidentifier",
        "runtimeidentifiers",
        "targetframework",
        "targetframeworks",
    }
)
_DOTNET_RESTORE_OWNED_OPTIONS = frozenset(
    {
        "--source",
        "-s",
        "--configfile",
        "--packages",
        "--no-http-cache",
        "--ignore-failed-sources",
        "--force",
        "--force-evaluate",
        "--locked-mode",
        "--use-lock-file",
        "--lock-file-path",
        "--disable-build-servers",
    }
)
_SECRET_MATERIAL = re.compile(
    rb"(?:-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"
    rb"|\bAKIA[0-9A-Z]{16}\b"
    rb"|\b(?:github_pat_|gh[pousr]_)[A-Za-z0-9_]{20,}\b"
    rb"|\bsk-[A-Za-z0-9_-]{20,}\b"
    rb"|\bxox[baprs]-[A-Za-z0-9-]{20,}\b"
    rb"|\beyJ[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{8,}\b)"
)
_EXACT_SECRET_VARIANTS: tuple[bytes, ...] = ()
_PYTEST_SHARD_PLUGIN = b'''"""Trusted deterministic pytest partitioner generated by DevCoordinator."""
import hashlib
import os


def pytest_collection_modifyitems(config, items):
    index = int(os.environ["DEVCOORDINATOR_TEST_SHARD_INDEX"])
    count = int(os.environ["DEVCOORDINATOR_TEST_SHARD_COUNT"])
    selected = []
    deselected = []
    for item in items:
        identity = hashlib.sha256(item.nodeid.encode("utf-8")).digest()
        (selected if int.from_bytes(identity[:8], "big") % count == index else deselected).append(item)
    if deselected:
        config.hook.pytest_deselected(items=deselected)
    items[:] = selected
'''


def _stable_file_identity(metadata: os.stat_result) -> tuple[int, ...]:
    return (
        metadata.st_dev,
        metadata.st_ino,
        stat.S_IFMT(metadata.st_mode),
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    )


def _write_all(descriptor: int, payload: bytes) -> None:
    """Write a complete bounded payload or fail without publishing it."""

    view = memoryview(payload)
    written = 0
    while written < len(view):
        count = os.write(descriptor, view[written:])
        if count <= 0:
            raise TestStoreContractError("runner result write did not make progress")
        written += count


def _suspected_secret(payload: bytes) -> bool:
    return _SECRET_MATERIAL.search(payload) is not None or any(
        material in payload for material in _EXACT_SECRET_VARIANTS
    )


def _credential_secret_variants(
    descriptor: TestAttemptDescriptor,
) -> tuple[bytes, ...]:
    if not descriptor.credentials:
        return ()
    raw_directory = os.environ.get("CREDENTIALS_DIRECTORY")
    if not raw_directory:
        raise TestStoreContractError("operational credential directory is unavailable")
    directory = Path(raw_directory)
    try:
        metadata = directory.lstat()
        resolved = directory.resolve(strict=True)
        entries = tuple(directory.iterdir())
    except OSError as error:
        raise TestStoreContractError(
            "operational credential directory is unavailable"
        ) from error
    if (
        not directory.is_absolute()
        or resolved != directory
        or not stat.S_ISDIR(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or len(entries) > 64
    ):
        raise TestStoreContractError("operational credential directory is unsafe")
    directory_identity = _stable_file_identity(metadata)
    variants: set[bytes] = set()
    for path in entries:
        try:
            path_before = path.lstat()
        except OSError as error:
            raise TestStoreContractError(
                "operational credential material is unavailable"
            ) from error
        if (
            not stat.S_ISREG(path_before.st_mode)
            or stat.S_ISLNK(path_before.st_mode)
        ):
            raise TestStoreContractError(
                "operational credential material is unsafe"
            )
        try:
            descriptor_fd = os.open(
                path,
                os.O_RDONLY | os.O_CLOEXEC | getattr(os, "O_NOFOLLOW", 0),
            )
        except OSError as error:
            raise TestStoreContractError(
                "operational credential material is unavailable"
            ) from error
        try:
            before = os.fstat(descriptor_fd)
            if (
                not stat.S_ISREG(before.st_mode)
            ):
                raise TestStoreContractError(
                    "operational credential material is unsafe"
                )
            if not 16 <= before.st_size <= 64 * 1024:
                continue
            payload = bytearray()
            while True:
                chunk = os.read(descriptor_fd, 64 * 1024)
                if not chunk:
                    break
                payload.extend(chunk)
                if len(payload) > 64 * 1024:
                    raise TestStoreContractError(
                        "operational credential material is excessive"
                    )
            os.lseek(descriptor_fd, 0, os.SEEK_SET)
            verification = bytearray()
            while True:
                chunk = os.read(descriptor_fd, 64 * 1024)
                if not chunk:
                    break
                verification.extend(chunk)
                if len(verification) > 64 * 1024:
                    raise TestStoreContractError(
                        "operational credential material is excessive"
                    )
            after = os.fstat(descriptor_fd)
        finally:
            os.close(descriptor_fd)
        try:
            current = path.lstat()
        except OSError as error:
            raise TestStoreContractError(
                "operational credential material changed"
            ) from error
        if (
            _stable_file_identity(before) != _stable_file_identity(after)
            or _stable_file_identity(after) != _stable_file_identity(current)
            or _stable_file_identity(current)
            != _stable_file_identity(path_before)
            or payload != verification
        ):
            raise TestStoreContractError("operational credential material changed")
        value = bytes(payload)
        variants.update(
            {
                value,
                base64.b64encode(value),
                base64.urlsafe_b64encode(value).rstrip(b"="),
                value.hex().encode("ascii"),
            }
        )
    try:
        directory_after = directory.lstat()
    except OSError as error:
        raise TestStoreContractError(
            "operational credential directory changed"
        ) from error
    if directory_identity != _stable_file_identity(directory_after):
        raise TestStoreContractError(
            "operational credential directory changed"
        )
    if not variants:
        raise TestStoreContractError("operational credential material is unavailable")
    return tuple(sorted(variants, key=lambda value: (-len(value), value)))


def _publish_pytest_shard_plugin(output: Path) -> Path:
    path = output / "devcoordinator_pytest_shard.py"
    path.unlink(missing_ok=True)
    descriptor = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        _write_all(descriptor, _PYTEST_SHARD_PLUGIN)
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    return path


def _resolve_executable(
    argv0: str, *, cwd: Path, environment: Mapping[str, str]
) -> Path:
    if "/" in argv0:
        candidate = Path(argv0)
        if not candidate.is_absolute():
            candidate = cwd / candidate
        try:
            executable = candidate.resolve(strict=True)
        except OSError as error:
            raise TestStoreContractError("test executable is unavailable") from error
    else:
        match = shutil.which(argv0, path=environment.get("PATH"))
        if match is None:
            raise TestStoreContractError("test executable is unavailable")
        executable = Path(match).resolve(strict=True)
    return executable


def _executable_provenance(
    argv0: str, *, cwd: Path, environment: Mapping[str, str]
) -> dict[str, object]:
    executable = _resolve_executable(argv0, cwd=cwd, environment=environment)
    try:
        descriptor = os.open(
            executable, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        )
    except OSError as error:
        raise TestStoreContractError("test executable cannot be observed") from error
    digest = hashlib.sha256()
    observed = 0
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode) or before.st_size > MAX_TOOLCHAIN_BYTES:
            raise TestStoreContractError("test executable provenance is unsafe")
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            observed += len(chunk)
            if observed > MAX_TOOLCHAIN_BYTES:
                raise TestStoreContractError("test executable provenance is unsafe")
            digest.update(chunk)
        after = os.fstat(descriptor)
    finally:
        os.close(descriptor)
    current = executable.lstat()
    if (
        (before.st_dev, before.st_ino, before.st_size)
        != (after.st_dev, after.st_ino, after.st_size)
        or (after.st_dev, after.st_ino, after.st_size)
        != (current.st_dev, current.st_ino, current.st_size)
        or observed != before.st_size
    ):
        raise TestStoreContractError("test executable changed while observed")
    return {
        "name": executable.name,
        "sha256": digest.hexdigest(),
        "size_bytes": observed,
    }


def _version_command(executable: Path, arguments: Sequence[str]) -> tuple[str, ...]:
    try:
        completed = subprocess.run(
            [str(executable), *arguments],
            cwd="/",
            env={
                "PATH": "/usr/local/bin:/usr/bin:/bin",
                "HOME": "/nonexistent",
                "LANG": "C.UTF-8",
                "LC_ALL": "C.UTF-8",
                "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1",
            },
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ()
    payload = completed.stdout[:64 * 1024]
    lines = []
    for raw in payload.decode("utf-8", errors="replace").splitlines()[:256]:
        value = raw.strip()
        if "[" in value:
            value = value.split("[", 1)[0].strip()
        if not value or "]" in value or "/" in value or "\\" in value:
            continue
        if len(value.encode("utf-8")) <= 512:
            lines.append(value)
    return tuple(lines)


def _transitive_toolchain_provenance(
    descriptor: TestAttemptDescriptor,
    *,
    cwd: Path,
    argv: Sequence[str],
    environment: Mapping[str, str],
) -> dict[str, object]:
    executable = _resolve_executable(argv[0], cwd=cwd, environment=environment)
    components: list[dict[str, object]] = []
    complete = descriptor.driver in {"pytest", "node", "dotnet"}
    commands: tuple[tuple[str, tuple[str, ...]], ...]
    if descriptor.driver == "pytest":
        commands = (
            ("python-runtime", ("--version",)),
            ("pytest-runtime", ("-m", "pytest", "--version")),
        )
    elif descriptor.driver == "node":
        commands = (("node-runtime", ("--version",)),)
    elif descriptor.driver == "dotnet":
        commands = (
            ("dotnet-sdk", ("--version",)),
            ("dotnet-runtimes", ("--list-runtimes",)),
            ("dotnet-sdks", ("--list-sdks",)),
        )
    else:
        commands = ()
    for name, arguments in commands:
        values = _version_command(executable, arguments)
        if not values:
            complete = False
        components.append(
            {
                "name": name,
                "arguments": list(arguments),
                "identities": list(values),
                "output_sha256": hashlib.sha256(
                    "\n".join(values).encode("utf-8")
                ).hexdigest(),
            }
        )
    source = dict(descriptor.source_provenance)
    if not source or source.get("complete") is not True:
        complete = False
    return {
        "complete": complete,
        "driver": descriptor.driver,
        "components": components,
        "source": source,
    }


def _write_execution_provenance(
    descriptor: TestAttemptDescriptor,
    *,
    output: Path,
    cwd: Path,
    argv: Sequence[str],
    environment: Mapping[str, str],
) -> Path:
    path = output / "execution-provenance.json"
    path.unlink(missing_ok=True)
    fixture_provenance: list[Mapping[str, object]] = []
    credential_directory = os.environ.get("CREDENTIALS_DIRECTORY")
    if descriptor.fixtures:
        if not credential_directory or not Path(credential_directory).is_absolute():
            raise TestStoreContractError("test fixture credentials are unavailable")
        provenance_file = Path(credential_directory) / "fixture-provenance.json"
        try:
            payload = provenance_file.read_bytes()
            decoded = json.loads(payload)
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise TestStoreContractError("test fixture provenance is unavailable") from error
        required = {
            "name", "template_id", "template_fingerprint", "image_ref",
            "full_container_id", "network", "secret_delivery",
        }
        if (
            len(payload) > 64 * 1024
            or not isinstance(decoded, list)
            or len(decoded) != len(descriptor.fixtures)
            or any(not isinstance(item, Mapping) or set(item) != required for item in decoded)
            or tuple(item["name"] for item in decoded) != descriptor.fixtures
            or any(
                not isinstance(item["template_id"], str)
                or not isinstance(item["template_fingerprint"], str)
                or re.fullmatch(r"sha256:[0-9a-f]{64}", item["template_fingerprint"]) is None
                or not isinstance(item["image_ref"], str)
                or re.search(r"@sha256:[0-9a-f]{64}$", item["image_ref"]) is None
                or not isinstance(item["full_container_id"], str)
                or re.fullmatch(r"[0-9a-f]{64}", item["full_container_id"]) is None
                or item["network"] not in {"private-loopback", "external"}
                or type(item["secret_delivery"]) is not bool
                for item in decoded
            )
        ):
            raise TestStoreContractError("test fixture provenance is invalid")
        fixture_provenance = [dict(item) for item in decoded]
    document = {
        "schema_version": 1,
        "attempt_id": descriptor.attempt_id,
        "repository_id": descriptor.repository_id,
        "repository_generation": descriptor.repository_generation,
        "source": {
            "mode": descriptor.source_mode,
            "snapshot_id": descriptor.snapshot_id,
        },
        "target": {
            "name": descriptor.target_name,
            "driver": descriptor.driver,
            "reporter": descriptor.reporter,
            "shard_index": descriptor.shard_index,
            "shard_count": descriptor.shard_count,
        },
        "descriptor_fingerprint": descriptor.fingerprint,
        "argv_fingerprint": hashlib.sha256(
            json.dumps(
                list(argv), separators=(",", ":"), ensure_ascii=False
            ).encode("utf-8")
        ).hexdigest(),
        "environment": {
            "names": sorted(environment),
            "fingerprint": hashlib.sha256(
                json.dumps(
                    dict(sorted(environment.items())),
                    separators=(",", ":"),
                    ensure_ascii=False,
                ).encode("utf-8")
            ).hexdigest(),
        },
        "executable": _executable_provenance(
            argv[0], cwd=cwd, environment=environment
        ),
        "toolchain": _transitive_toolchain_provenance(
            descriptor,
            cwd=cwd,
            argv=argv,
            environment=environment,
        ),
        "fixtures": fixture_provenance,
        "runner": {
            "python": ".".join(str(item) for item in sys.version_info[:3]),
            "kernel": os.uname().release,
            "machine": os.uname().machine,
        },
    }
    payload = _json_bytes(document, maximum=64 * 1024)
    descriptor_fd = os.open(
        path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        _write_all(descriptor_fd, payload)
        os.fsync(descriptor_fd)
    finally:
        os.close(descriptor_fd)
    return path


def _load(path: Path) -> tuple[TestAttemptDescriptor, Path, Path]:
    metadata = path.lstat()
    if (
        not stat.S_ISREG(metadata.st_mode)
        or metadata.st_size > MAX_LAUNCH_BYTES
    ):
        raise TestStoreContractError("runner launch descriptor is unsafe")
    document = json.loads(path.read_bytes())
    base_fields = {
        "schema_version",
        "descriptor",
        "descriptor_fingerprint",
        "output_root",
        "result_path",
    }
    if not isinstance(document, Mapping):
        raise TestStoreContractError("runner launch descriptor fields are invalid")
    schema_version = document.get("schema_version")
    fields = set(document)
    if type(schema_version) is not int or (
        schema_version == 1 and fields != base_fields
    ) or (
        schema_version == 2 and fields != base_fields | {"launch_ticket_id"}
    ) or schema_version not in {1, 2}:
        raise TestStoreContractError("runner launch descriptor fields are invalid")
    if not isinstance(document["descriptor"], Mapping):
        raise TestStoreContractError("runner launch descriptor fields are invalid")
    if schema_version == 2:
        try:
            launch_ticket_id = _safe_id(
                "launch_ticket_id", document["launch_ticket_id"]
            )
        except TestStoreContractError as error:
            raise TestStoreContractError(
                "runner launch descriptor fields are invalid"
            ) from error
        if not launch_ticket_id.startswith("test-ticket-"):
            raise TestStoreContractError(
                "runner launch descriptor fields are invalid"
            )
    descriptor = TestAttemptDescriptor.from_document(document["descriptor"])
    if descriptor.fingerprint != document["descriptor_fingerprint"]:
        raise TestStoreContractError("runner launch descriptor fingerprint is invalid")
    if os.geteuid() != descriptor.owner_uid:
        raise TestStoreContractError("runner owner identity is invalid")
    result_path = Path(str(document["result_path"]))
    output_root = Path(str(document["output_root"]))
    try:
        output_metadata = output_root.lstat()
        resolved_output = output_root.resolve(strict=True)
    except OSError as error:
        raise TestStoreContractError("runner output root is unavailable") from error
    if (
        not output_root.is_absolute()
        or resolved_output != output_root
        or not stat.S_ISDIR(output_metadata.st_mode)
        or stat.S_ISLNK(output_metadata.st_mode)
        or result_path.parent != output_root
        or result_path.name != "result.json"
    ):
        raise TestStoreContractError("runner output boundary is unsafe")
    return descriptor, output_root, result_path


def _capture(stream, destination: Path, state: dict[str, object]) -> None:
    observed_digest = hashlib.sha256()
    retained_digest = hashlib.sha256()
    retained = 0
    total = 0
    truncated = False
    descriptor = os.open(
        destination,
        os.O_RDWR | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    state["_descriptor"] = descriptor
    output_descriptor = os.dup(descriptor)
    with os.fdopen(output_descriptor, "wb", buffering=0) as output:
        os.fchmod(descriptor, 0o600)
        while True:
            chunk = stream.read(64 * 1024)
            if not chunk:
                break
            total += len(chunk)
            observed_digest.update(chunk)
            if retained < MAX_CAPTURE_BYTES:
                keep = chunk[: MAX_CAPTURE_BYTES - retained]
                output.write(keep)
                retained_digest.update(keep)
                retained += len(keep)
            if total > MAX_CAPTURE_BYTES:
                truncated = True
        os.fsync(descriptor)
    identity = os.fstat(descriptor)
    state.update(
        {
            # ``sha256`` is the complete observed stream identity.  The
            # retained artifact has its own digest because a bounded capture
            # may be truncated.
            "sha256": observed_digest.hexdigest(),
            "retained_sha256": retained_digest.hexdigest(),
            "size_bytes": retained,
            "observed_bytes": total,
            "truncated": truncated,
            "device": identity.st_dev,
            "inode": identity.st_ino,
        }
    )


def _redact_capture_if_needed(path: Path, state: dict[str, object]) -> None:
    descriptor = state.get("_descriptor")
    if type(descriptor) is not int:
        raise TestStoreContractError("runner capture descriptor is unavailable")
    os.lseek(descriptor, 0, os.SEEK_SET)
    payload = os.read(descriptor, MAX_CAPTURE_BYTES + 1)
    if not _suspected_secret(payload):
        state["secret_redacted"] = False
        return
    replacement = b"[redacted: suspected secret material]\n"
    os.ftruncate(descriptor, 0)
    os.lseek(descriptor, 0, os.SEEK_SET)
    _write_all(descriptor, replacement)
    os.fsync(descriptor)
    state.update(
        {
            "retained_sha256": hashlib.sha256(replacement).hexdigest(),
            "size_bytes": len(replacement),
            "secret_redacted": True,
        }
    )


def _digest_private_file(
    path: Path,
    *,
    maximum_bytes: int,
    field: str,
) -> tuple[str, int]:
    descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
    try:
        before = os.fstat(descriptor)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_size > maximum_bytes
        ):
            raise TestStoreContractError(f"{field} is unsafe")
        digest = hashlib.sha256()
        observed = 0
        tail = b""
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            observed += len(chunk)
            if observed > maximum_bytes:
                raise TestStoreContractError(f"{field} exceeds its bound")
            digest.update(chunk)
            scan = tail + chunk
            if _suspected_secret(scan):
                raise TestStoreContractError(
                    f"{field} contains suspected secret material"
                )
            tail = scan[-4096:]
        after = os.fstat(descriptor)
        path_after = path.lstat()
        if (
            _stable_file_identity(before) != _stable_file_identity(after)
            or _stable_file_identity(after)
            != _stable_file_identity(path_after)
        ):
            raise TestStoreContractError(f"{field} changed during read")
        return digest.hexdigest(), observed
    finally:
        os.close(descriptor)


def _capture_artifact(
    descriptor: TestAttemptDescriptor,
    *,
    stream_name: str,
    path: Path,
    state: Mapping[str, object],
) -> Mapping[str, object]:
    """Publish one bounded capture through the typed artifact contract.

    The public handle is opaque and contains no server filesystem path.  The
    exact private path remains only in the broker-owned runner result envelope
    so a protected artifact collector can resolve it before attempt cleanup.
    """

    if stream_name not in {"stdout", "stderr"}:
        raise TestStoreContractError("capture artifact kind is invalid")
    metadata = path.lstat()
    retained_sha256 = state.get("retained_sha256")
    size_bytes = state.get("size_bytes")
    if (
        not stat.S_ISREG(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or not isinstance(retained_sha256, str)
        or len(retained_sha256) != 64
        or type(size_bytes) is not int
        or size_bytes != metadata.st_size
        or size_bytes > MAX_CAPTURE_BYTES
        or (metadata.st_dev, metadata.st_ino)
        != (state.get("device"), state.get("inode"))
    ):
        raise TestStoreContractError("runner capture artifact is unsafe")
    artifact_id = "artifact-" + hashlib.sha256(
        (
            descriptor.attempt_id
            + "\0capture\0"
            + stream_name
            + "\0"
            + retained_sha256
        ).encode("utf-8")
    ).hexdigest()[:32]
    return {
        "artifact_id": artifact_id,
        "kind": "log",
        "storage_handle": f"test-artifact://{artifact_id}/{retained_sha256}",
        "sha256": retained_sha256,
        "size_bytes": size_bytes,
        "verified": True,
        "_source_path": str(path),
    }


def _contained(root: Path, relative: object) -> Path:
    if not isinstance(relative, str) or not relative or relative.startswith("/"):
        raise TestStoreContractError("runner artifact path is invalid")
    candidate = (root / relative).resolve(strict=True)
    if candidate != root and root not in candidate.parents:
        raise TestStoreContractError("runner artifact path escapes attempt root")
    return candidate


def _artifact(
    descriptor: TestAttemptDescriptor,
    root: Path,
    output: Path,
    policy: Mapping[str, object],
) -> Mapping[str, object] | None:
    try:
        path = _contained(root, policy["path"])
    except (OSError, TestStoreContractError):
        if policy["required"] is True:
            raise TestStoreContractError(
                f"required artifact is missing: {policy['name']}"
            )
        return None
    metadata = path.lstat()
    if policy["kind"] == "directory":
        if _suspected_secret(os.fsencode(str(policy["path"]))):
            raise TestStoreContractError(
                "runner directory artifact path contains secret material"
            )
        if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            raise TestStoreContractError("runner directory artifact is unsafe")
        archive_name = "directory-" + hashlib.sha256(
            (descriptor.attempt_id + "\0" + str(policy["name"])).encode("utf-8")
        ).hexdigest()[:32] + ".tar"
        archive_path = output / archive_name
        archive_path.unlink(missing_ok=True)
        archive_fd = os.open(
            archive_path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        try:
            with os.fdopen(os.dup(archive_fd), "wb", closefd=True) as destination:
                evidence = package_directory(
                    path,
                    destination,
                    expected_uid=os.geteuid(),
                    maximum_bytes=int(policy["max_bytes"]),
                    prohibited_sequences=_EXACT_SECRET_VARIANTS,
                )
                destination.flush()
            os.fsync(archive_fd)
        except Exception:
            archive_path.unlink(missing_ok=True)
            raise
        finally:
            os.close(archive_fd)
        artifact_id = "artifact-" + hashlib.sha256(
            (
                descriptor.attempt_id
                + "\0"
                + str(policy["name"])
                + "\0"
                + evidence.sha256
            ).encode("utf-8")
        ).hexdigest()[:32]
        return {
            "artifact_id": artifact_id,
            "kind": "directory",
            "storage_handle": f"test-artifact://{artifact_id}/{evidence.sha256}",
            "sha256": evidence.sha256,
            "size_bytes": evidence.size_bytes,
            "verified": True,
            "_source_path": str(archive_path),
            "_packaged_from_path": str(path),
        }
    if not stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
        raise TestStoreContractError("runner artifact is not a regular file")
    digest, size = _digest_private_file(
        path,
        maximum_bytes=int(policy["max_bytes"]),
        field=f"artifact {policy['name']}",
    )
    artifact_id = "artifact-" + hashlib.sha256(
        (
            descriptor.attempt_id
            + "\0"
            + str(policy["name"])
            + "\0"
            + digest
        ).encode("utf-8")
    ).hexdigest()[:32]
    return {
        "artifact_id": artifact_id,
        "kind": policy["kind"],
        "storage_handle": f"test-artifact://{artifact_id}/{digest}",
        "sha256": digest,
        "size_bytes": size,
        "verified": True,
        "_source_path": str(path),
    }


def _generated_artifact(
    descriptor: TestAttemptDescriptor,
    path: Path,
    *,
    kind: str,
    name: str,
) -> Mapping[str, object]:
    metadata = path.lstat()
    if (
        not stat.S_ISREG(metadata.st_mode)
        or stat.S_ISLNK(metadata.st_mode)
        or metadata.st_size > MAX_REPORT_BYTES
    ):
        raise TestStoreContractError("generated reporter artifact is unsafe")
    digest, observed_size = _digest_private_file(
        path,
        maximum_bytes=MAX_REPORT_BYTES,
        field="generated reporter artifact",
    )
    artifact_id = "artifact-" + hashlib.sha256(
        (descriptor.attempt_id + "\0" + name + "\0" + digest).encode("utf-8")
    ).hexdigest()[:32]
    return {
        "artifact_id": artifact_id,
        "kind": kind,
        "storage_handle": f"test-artifact://{artifact_id}/{digest}",
        "sha256": digest,
        "size_bytes": observed_size,
        "verified": True,
        "_source_path": str(path),
    }


def _directory_failure_diagnostic(
    descriptor: TestAttemptDescriptor,
    artifacts: Sequence[Mapping[str, object]],
    *,
    output: Path,
) -> Mapping[str, object] | None:
    """Project bounded text tails from already verified directory archives."""

    chunks: list[bytes] = []
    retained = 0
    allowed_suffixes = {".json", ".jsonl", ".log", ".txt", ".xml"}
    private_roots: dict[str, bytes] = {}
    for private_root, replacement in (
        (descriptor.original_root, b"<repository>"),
        (descriptor.execution_root, b"<execution-root>"),
        (descriptor.worktree_key, b"<worktree>"),
        (str(output), b"<attempt-output>"),
    ):
        private_roots.setdefault(str(Path(private_root)), replacement)
    if descriptor.temporary_root is not None:
        private_roots.setdefault(str(Path(descriptor.temporary_root)),
            b"<temporary-repository>"
        )
    for artifact in artifacts:
        if artifact.get("kind") != "directory":
            continue
        archive_text = artifact.get("_source_path")
        if not isinstance(archive_text, str):
            raise TestStoreContractError("runner directory artifact source is missing")
        archive = Path(archive_text)
        with tarfile.open(archive, mode="r:") as packaged:
            for member in packaged.getmembers():
                member_path = PurePosixPath(member.name)
                if (
                    not member.isfile()
                    or member.size <= 0
                    or member.size > MAX_REPORT_BYTES
                    or member_path.is_absolute()
                    or any(part in {".", ".."} for part in member_path.parts)
                    or member_path.suffix.lower() not in allowed_suffixes
                ):
                    continue
                source = packaged.extractfile(member)
                if source is None:
                    continue
                payload = source.read(MAX_REPORT_BYTES + 1)
                if len(payload) != member.size or b"\0" in payload:
                    continue
                tail = payload[-MAX_FAILURE_DIAGNOSTIC_FILE_BYTES:]
                for private_root, replacement in sorted(
                    private_roots.items(), key=lambda item: len(item[0]), reverse=True
                ):
                    tail = tail.replace(os.fsencode(private_root), replacement)
                text = tail.decode("utf-8", errors="replace")
                if text and (
                    sum(character.isprintable() or character in "\r\n\t" for character in text)
                    / len(text)
                ) < 0.85:
                    continue
                header = f"== {member_path.as_posix()} ==\n".encode("utf-8")
                candidate = header + tail + (b"" if tail.endswith(b"\n") else b"\n")
                available = MAX_FAILURE_DIAGNOSTIC_BYTES - retained
                if available <= 0:
                    break
                selected = candidate[:available]
                chunks.append(selected)
                retained += len(selected)
            if retained >= MAX_FAILURE_DIAGNOSTIC_BYTES:
                break
    if not chunks:
        return None
    path = output / "failure-diagnostics.log"
    path.write_bytes(b"".join(chunks))
    return _generated_artifact(
        descriptor,
        path,
        kind="log",
        name="failure-diagnostics",
    )


def _artifact_sources(
    artifacts: Sequence[Mapping[str, object]],
    *,
    output: Path,
    execution_root: Path,
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    """Separate private collection paths from public exact-ID metadata."""

    public: list[dict[str, object]] = []
    sources: list[dict[str, object]] = []
    for raw in artifacts:
        value = dict(raw)
        source_text = value.pop("_source_path", None)
        packaged_from_text = value.pop("_packaged_from_path", None)
        if not isinstance(source_text, str):
            raise TestStoreContractError("runner artifact source is missing")
        source = Path(source_text)
        try:
            relative = source.relative_to(output)
            scope = "output"
        except ValueError:
            try:
                relative = source.relative_to(execution_root)
                scope = "execution"
            except ValueError as error:
                raise TestStoreContractError(
                    "runner artifact source escapes trusted roots"
                ) from error
        if not relative.parts or any(part in {".", ".."} for part in relative.parts):
            raise TestStoreContractError("runner artifact relative path is invalid")
        public.append(value)
        packaged_from: str | None = None
        if packaged_from_text is not None:
            if value.get("kind") != "directory" or not isinstance(packaged_from_text, str):
                raise TestStoreContractError("runner directory artifact source is invalid")
            try:
                packaged_from = Path(packaged_from_text).relative_to(execution_root).as_posix()
            except ValueError as error:
                raise TestStoreContractError(
                    "runner directory artifact source escapes execution root"
                ) from error
        sources.append(
            {
                "artifact_id": value["artifact_id"],
                "storage_handle": value["storage_handle"],
                "kind": value["kind"],
                "scope": scope,
                "relative_path": relative.as_posix(),
                "packaged_from": packaged_from,
                "sha256": value["sha256"],
                "size_bytes": value["size_bytes"],
            }
        )
    return public, sources


def adapt_driver_invocation(
    descriptor: TestAttemptDescriptor, output: Path
) -> tuple[tuple[str, ...], dict[str, str], Path, str]:
    """Return one fixed no-shell reporter adapter for the typed driver."""

    environment = dict(descriptor.environment)
    environment.update(
        {
            "DEVCOORDINATOR_TEST_SHARD_INDEX": str(descriptor.shard_index),
            "DEVCOORDINATOR_TEST_SHARD_COUNT": str(descriptor.shard_count),
        }
    )
    argv = tuple(descriptor.argv)
    is_dotnet_invocation = _is_dotnet_project_invocation(descriptor)
    if is_dotnet_invocation:
        # Apply the same trusted, attempt-local CLI state to a typed dotnet
        # test and to an automation target whose exact executable is dotnet.
        environment.update(
            {
                "DOTNET_CLI_HOME": str(output / "dotnet-cli-home"),
                "DOTNET_CLI_TELEMETRY_OPTOUT": "1",
                "DOTNET_NOLOGO": "1",
                "DOTNET_SKIP_FIRST_TIME_EXPERIENCE": "1",
                "DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE": "1",
            }
        )
    if descriptor.driver == "pytest":
        reporter = output / "reporter.junit.xml"
        if descriptor.shard_count > 1:
            _publish_pytest_shard_plugin(output)
            inherited_pythonpath = environment.get("PYTHONPATH")
            environment["PYTHONPATH"] = str(output) + (
                "" if inherited_pythonpath is None else os.pathsep + inherited_pythonpath
            )
            argv += ("-p", "devcoordinator_pytest_shard")
        argv += ("--junitxml", str(reporter))
        kind = "junit"
    elif descriptor.driver == "dotnet":
        reporter = output / "reporter.trx"
        # A fresh attempt HOME must not turn every dotnet invocation into a
        # first-use/workload-maintenance operation.  Keep all mutable CLI state
        # inside the attempt output and make the non-test SDK behavior fixed by
        # the trusted adapter rather than repository-controlled environment.
        dotnet_arguments = argv[2:]
        passthrough = (
            dotnet_arguments.index("--")
            if "--" in dotnet_arguments
            else len(dotnet_arguments)
        )
        if (
            _dotnet_locked_restore_required(descriptor)
            and "--no-build" in dotnet_arguments[:passthrough]
        ):
            # Dependency targets run in separate immutable attempts; their
            # writable build output is deliberately not shared.  Let this
            # test attempt build from its already sealed offline restore.
            before_passthrough = tuple(
                argument
                for argument in dotnet_arguments[:passthrough]
                if argument != "--no-build"
            )
            dotnet_arguments = (
                *before_passthrough,
                *dotnet_arguments[passthrough:],
            )
            argv = (*argv[:2], *dotnet_arguments)
            passthrough = len(before_passthrough)
        trusted_options: tuple[str, ...] = ()
        if (
            _dotnet_locked_restore_required(descriptor)
            and "--no-restore" not in dotnet_arguments[:passthrough]
        ):
            # The trusted bootstrap below performs the exact offline locked
            # restore.  Project execution must not silently contact sources or
            # repeat audit/restore work afterward.
            trusted_options += ("--no-restore",)
        trusted_options += (
            "--logger",
            f"trx;LogFileName={reporter.name}",
            "--results-directory",
            str(output),
        )
        insertion = 2 + passthrough
        argv = (*argv[:insertion], *trusted_options, *argv[insertion:])
        kind = "trx"
    elif descriptor.driver == "node" and any(
        argument == "--test" or argument.startswith("--test=")
        for argument in argv[1:]
    ):
        reporter = output / "reporter.junit.xml"
        node_options = [
            "--test-reporter=junit",
            f"--test-reporter-destination={reporter}",
        ]
        if descriptor.shard_count > 1:
            node_options.append(
                "--test-shard="
                f"{descriptor.shard_index + 1}/{descriptor.shard_count}"
            )
        # Node stops parsing CLI options after the first positional test path.
        # Inject trusted reporter/shard options immediately after the executable
        # so repository-declared paths cannot turn them into file arguments.
        argv = (argv[0], *node_options, *argv[1:])
        kind = "junit"
    else:
        reporter = output / "reporter.events.jsonl"
        environment["DEVCOORDINATOR_TEST_EVENTS"] = str(reporter)
        environment["DEVCOORDINATOR_TEST_RESULTS"] = str(reporter)
        kind = "jsonl"
    return argv, environment, reporter, kind


class DotnetReadinessFailure(NamedTuple):
    stage: str
    returncode: int
    stdout: bytes
    stderr: bytes
    global_json: Path | None
    sdk_version: str | None
    sdk_unavailable: bool


class DotnetProbeResult(NamedTuple):
    returncode: int
    stdout: bytes
    stderr: bytes
    timed_out: bool


def _is_dotnet_project_invocation(descriptor: TestAttemptDescriptor) -> bool:
    return (
        len(descriptor.argv) >= 2
        and (
            descriptor.driver == "dotnet"
            or Path(descriptor.argv[0]).name == "dotnet"
        )
        and descriptor.argv[1] in {"build", "test"}
    )


def _dotnet_locked_restore_required(descriptor: TestAttemptDescriptor) -> bool:
    return descriptor.source_mode == "immutable" and any(
        binding.get("kind") == "dotnet-packages"
        for binding in descriptor.dependency_bindings
    )


def _immutable_python_launch_executable(
    descriptor: TestAttemptDescriptor,
) -> str | None:
    """Return the private mount executable for an external venv toolchain.

    ``argv[0]`` intentionally remains the environment executable so CPython
    discovers the mounted venv and its ``pyvenv.cfg``.  ``Popen.executable``
    selects the same fingerprinted interpreter through the unit-private mount,
    avoiding traversal through an absolute symlink into another local home.
    """

    if descriptor.source_mode != "immutable":
        return None
    for binding in descriptor.dependency_bindings:
        toolchain = binding.get("toolchain")
        if not isinstance(toolchain, Mapping):
            continue
        if toolchain.get("installation_kind") != "python-toolchain":
            continue
        source = Path(str(toolchain["source_root"]))
        resolved = Path(str(toolchain["resolved_executable"]))
        try:
            relative = resolved.relative_to(source)
        except ValueError as error:
            raise TestStoreContractError(
                "immutable Python toolchain executable escapes its root"
            ) from error
        if not relative.parts or any(part in {".", ".."} for part in relative.parts):
            raise TestStoreContractError(
                "immutable Python toolchain executable is invalid"
            )
        return str(_IMMUTABLE_PYTHON_TOOLCHAIN_MOUNT / relative)
    return None


def _dotnet_restore_project(
    argv: Sequence[str], *, cwd: Path, execution_root: Path
) -> Path:
    """Resolve the one typed project operand without leaving the snapshot."""

    if len(argv) < 2 or argv[1] not in {"build", "test"}:
        raise TestStoreContractError(
            "locked dotnet bootstrap requires a dotnet build or test invocation"
        )
    candidates: list[str] = []
    for raw in argv[2:]:
        if raw == "--":
            break
        if raw.startswith("-"):
            continue
        if Path(raw).suffix.lower() in _DOTNET_RESTORE_PROJECT_SUFFIXES:
            candidates.append(raw)
    if len(candidates) != 1:
        raise TestStoreContractError(
            "locked dotnet bootstrap requires exactly one project or solution"
        )
    root = execution_root.resolve(strict=True)
    candidate = Path(candidates[0])
    if not candidate.is_absolute():
        candidate = cwd / candidate
    try:
        before = candidate.lstat()
        resolved = candidate.resolve(strict=True)
        after = candidate.lstat()
    except OSError as error:
        raise TestStoreContractError(
            "locked dotnet project could not be opened safely"
        ) from error
    if (
        stat.S_ISLNK(before.st_mode)
        or not stat.S_ISREG(before.st_mode)
        or _stable_file_identity(before) != _stable_file_identity(after)
        or (resolved != root and root not in resolved.parents)
    ):
        raise TestStoreContractError("locked dotnet project is unsafe")
    return resolved


def _dotnet_restore_semantic_options(argv: Sequence[str]) -> tuple[str, ...]:
    """Retain only bounded graph-selection options; own all source/cache policy."""

    forwarded: list[str] = []
    index = 2
    while index < len(argv) and argv[index] != "--":
        raw = argv[index]
        option_name = raw.split("=", 1)[0].lower()
        if option_name in _DOTNET_RESTORE_OWNED_OPTIONS:
            raise TestStoreContractError(
                "dotnet restore feed and cache options are runner-owned"
            )
        if raw in _DOTNET_RESTORE_VALUE_OPTIONS:
            if (
                index + 1 >= len(argv)
                or argv[index + 1] == "--"
                or argv[index + 1].startswith("-")
            ):
                raise TestStoreContractError(
                    "dotnet restore graph option is missing its value"
                )
            value = argv[index + 1]
            if raw in {"--configuration", "-c"}:
                forwarded.append(f"-p:Configuration={value}")
            elif raw in {"--framework", "-f"}:
                forwarded.append(f"-p:TargetFramework={value}")
            else:
                forwarded.extend((raw, value))
            index += 2
            continue
        if any(
            raw.startswith(option + "=")
            for option in _DOTNET_RESTORE_VALUE_OPTIONS
            if option.startswith("--")
        ):
            if not raw.split("=", 1)[1]:
                raise TestStoreContractError(
                    "dotnet restore graph option is missing its value"
                )
            option, value = raw.split("=", 1)
            if option == "--configuration":
                forwarded.append(f"-p:Configuration={value}")
            elif option == "--framework":
                forwarded.append(f"-p:TargetFramework={value}")
            else:
                forwarded.append(raw)
            index += 1
            continue
        property_prefix = next(
            (
                prefix
                for prefix in ("-p:", "/p:", "--property:")
                if raw.lower().startswith(prefix)
            ),
            None,
        )
        if property_prefix is not None:
            assignment = raw[len(property_prefix) :]
            name, separator, value = assignment.partition("=")
            if name.lower() == "restorelockedmode":
                if separator and value.lower() in {"1", "true"}:
                    index += 1
                    continue
                raise TestStoreContractError(
                    "dotnet locked restore policy is runner-owned"
                )
            if (
                not separator
                or not value
                or name.lower() not in _DOTNET_RESTORE_GRAPH_PROPERTIES
            ):
                raise TestStoreContractError(
                    "dotnet restore MSBuild property is not an allowed graph selector"
                )
            forwarded.append(raw)
        index += 1
    return tuple(forwarded)


def _dotnet_locked_restore_command(
    argv: Sequence[str],
    *,
    cwd: Path,
    execution_root: Path,
    environment: Mapping[str, str],
    packages: Path,
    config_file: Path,
) -> tuple[str, ...]:
    """Build one trusted local-source restore from a typed ``dotnet test`` argv."""

    project = _dotnet_restore_project(argv, cwd=cwd, execution_root=execution_root)
    semantic_options = _dotnet_restore_semantic_options(argv)
    packages_raw = environment.get("NUGET_PACKAGES")
    source_raw = environment.get("DEVCOORDINATOR_NUGET_SOURCE")
    if (
        not packages_raw
        or not source_raw
        or not Path(packages_raw).is_absolute()
        or not Path(source_raw).is_absolute()
    ):
        raise TestStoreContractError("locked dotnet package source is unavailable")
    try:
        resolved_packages = Path(packages_raw).resolve(strict=True)
        resolved_source = Path(source_raw).resolve(strict=True)
        resolved_config = config_file.resolve(strict=True)
        root = execution_root.resolve(strict=True)
    except OSError as error:
        raise TestStoreContractError(
            "locked dotnet package source is unavailable"
        ) from error
    expected_source = root.joinpath(
        *PurePosixPath(_DOTNET_NUGET_SOURCE_DESTINATION).parts
    )
    try:
        source_metadata = Path(source_raw).lstat()
        packages_metadata = packages.lstat()
    except OSError as error:
        raise TestStoreContractError(
            "locked dotnet package source is unavailable"
        ) from error
    if (
        resolved_packages != packages.resolve(strict=True)
        or resolved_packages != packages
        or Path(packages_raw) != packages
        or not stat.S_ISDIR(packages_metadata.st_mode)
        or stat.S_ISLNK(packages_metadata.st_mode)
        or resolved_source != expected_source
        or Path(source_raw) != expected_source
        or not stat.S_ISDIR(source_metadata.st_mode)
        or stat.S_ISLNK(source_metadata.st_mode)
        or next(resolved_source.glob("*/*/*.nupkg"), None) is None
        or resolved_config != config_file
        or not config_file.is_file()
        or config_file.read_text(encoding="utf-8")
        != "<configuration><packageSources><clear /></packageSources></configuration>\n"
    ):
        raise TestStoreContractError("locked dotnet package source is unavailable")
    return (
        argv[0],
        "restore",
        str(project),
        *semantic_options,
        "--locked-mode",
        "--force",
        "--packages",
        str(resolved_packages),
        "--source",
        str(resolved_source),
        "--configfile",
        str(resolved_config),
        "--no-http-cache",
        "--disable-build-servers",
        "-p:NuGetAudit=false",
        "--verbosity",
        "minimal",
    )


def _drain_dotnet_probe_stream(
    stream, state: dict[str, object], *, stream_name: str
) -> None:
    retained = bytearray()
    observed = 0
    while True:
        chunk = stream.read(64 * 1024)
        if not chunk:
            break
        observed += len(chunk)
        if len(retained) < MAX_DOTNET_READINESS_STREAM_BYTES:
            retained.extend(
                chunk[
                    : MAX_DOTNET_READINESS_STREAM_BYTES - len(retained)
                ]
            )
    if observed > len(retained):
        marker = (
            f"\n[DevCoordinator truncated dotnet {stream_name} readiness output; "
            f"observed {observed} bytes]\n"
        ).encode("utf-8")[:MAX_DOTNET_READINESS_STREAM_BYTES]
        keep = max(0, MAX_DOTNET_READINESS_STREAM_BYTES - len(marker))
        retained = retained[:keep] + marker
    state["payload"] = bytes(retained)
    state["observed_bytes"] = observed


def _run_dotnet_probe(
    command: Sequence[str],
    *,
    cwd: Path,
    environment: Mapping[str, str],
    timeout_seconds: float,
) -> DotnetProbeResult:
    """Run a probe while draining both streams without unbounded buffering."""

    process = subprocess.Popen(
        list(command),
        cwd=cwd,
        env=dict(environment),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        start_new_session=True,
    )
    if process.stdout is None or process.stderr is None:
        process.kill()
        process.wait()
        raise subprocess.SubprocessError("dotnet readiness pipes are unavailable")
    stdout_state: dict[str, object] = {}
    stderr_state: dict[str, object] = {}
    threads = (
        threading.Thread(
            target=_drain_dotnet_probe_stream,
            args=(process.stdout, stdout_state),
            kwargs={"stream_name": "stdout"},
        ),
        threading.Thread(
            target=_drain_dotnet_probe_stream,
            args=(process.stderr, stderr_state),
            kwargs={"stream_name": "stderr"},
        ),
    )
    for thread in threads:
        thread.start()
    timed_out = False
    try:
        returncode = process.wait(timeout=timeout_seconds)
    except subprocess.TimeoutExpired:
        timed_out = True
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            process.kill()
        returncode = process.wait()
    else:
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
    for thread in threads:
        thread.join()
    process.stdout.close()
    process.stderr.close()
    return DotnetProbeResult(
        124 if timed_out else int(returncode),
        bytes(stdout_state.get("payload", b"")),
        bytes(stderr_state.get("payload", b"")),
        timed_out,
    )


def _dotnet_global_json(
    argv: Sequence[str], *, cwd: Path, execution_root: Path
) -> Path | None:
    """Resolve the SDK policy nearest the declared project, within the snapshot."""

    root = execution_root.resolve(strict=True)
    starts: list[Path] = []
    for raw in argv[1:]:
        if not raw or raw.startswith("-"):
            continue
        candidate = Path(raw)
        if not candidate.is_absolute():
            candidate = cwd / candidate
        try:
            resolved = candidate.resolve(strict=True)
        except OSError:
            continue
        if resolved != root and root not in resolved.parents:
            continue
        if resolved.is_dir() or resolved.suffix.lower() in _DOTNET_PROJECT_SUFFIXES:
            starts.append(resolved if resolved.is_dir() else resolved.parent)
            break
    starts.append(cwd)
    for start in starts:
        for directory in (start, *start.parents):
            if directory != root and root not in directory.parents:
                break
            candidate = directory / "global.json"
            if candidate.is_file():
                return candidate
            if directory == root:
                break
    return None


def _dotnet_sdk_version(global_json: Path | None) -> str | None:
    if global_json is None:
        return None
    try:
        metadata = global_json.stat()
        if metadata.st_size > MAX_DOTNET_GLOBAL_JSON_BYTES:
            return None
        document = json.loads(global_json.read_bytes())
    except (OSError, ValueError):
        return None
    if not isinstance(document, Mapping) or not isinstance(document.get("sdk"), Mapping):
        return None
    version = document["sdk"].get("version")
    return version if isinstance(version, str) and 0 < len(version) <= 128 else None


def _dotnet_readiness(
    argv: Sequence[str],
    *,
    cwd: Path,
    execution_root: Path,
    environment: Mapping[str, str],
    timeout_seconds: int,
    locked_restore: bool = False,
    output: Path | None = None,
    deadline: float | None = None,
) -> DotnetReadinessFailure | None:
    """Validate SDK selection and trusted restore before project execution."""

    global_json = _dotnet_global_json(argv, cwd=cwd, execution_root=execution_root)
    sdk_version = _dotnet_sdk_version(global_json)
    readiness_cwd = global_json.parent if global_json is not None else cwd
    deadline = (
        time.monotonic() + timeout_seconds if deadline is None else deadline
    )
    probes: tuple[tuple[str, tuple[str, ...], Path], ...] = (
        ("sdk", (argv[0], "--version"), readiness_cwd),
    )
    if locked_restore:
        try:
            if output is None:
                raise TestStoreContractError(
                    "locked dotnet bootstrap output is unavailable"
                )
            packages = output / "nuget-packages"
            try:
                packages.mkdir(mode=0o700)
            except FileExistsError:
                metadata = packages.lstat()
                if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                    raise TestStoreContractError(
                        "locked dotnet writable package cache is unsafe"
                    )
            if any(packages.iterdir()):
                raise TestStoreContractError(
                    "locked dotnet writable package cache is not empty"
                )
            environment["NUGET_PACKAGES"] = str(packages)
            config_file = output / "NuGet.Config"
            try:
                config_file.write_text(
                    "<configuration><packageSources><clear /></packageSources>"
                    "</configuration>\n",
                    encoding="utf-8",
                )
                config_file.chmod(0o600)
            except OSError as error:
                raise TestStoreContractError(
                    "locked dotnet source configuration is unavailable"
                ) from error
            restore = _dotnet_locked_restore_command(
                argv,
                cwd=cwd,
                execution_root=execution_root,
                environment=environment,
                packages=packages,
                config_file=config_file,
            )
        except (OSError, TestStoreContractError) as error:
            detail = (" ".join(str(error).split()) or type(error).__name__)[:2048]
            return DotnetReadinessFailure(
                "restore",
                127,
                b"",
                (
                    "DevCoordinator could not prepare the trusted offline "
                    f"dotnet restore ({type(error).__name__}): {detail}\n"
                ).encode("utf-8", errors="replace"),
                global_json,
                sdk_version,
                False,
            )
        probes += (("restore", restore, cwd),)
    for stage, command, probe_cwd in probes:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return DotnetReadinessFailure(
                stage,
                124,
                b"",
                (
                    "DevCoordinator dotnet readiness exhausted the caller's "
                    f"{timeout_seconds}s execution timeout before project tests.\n"
                ).encode("utf-8"),
                global_json,
                sdk_version,
                False,
            )
        try:
            completed = _run_dotnet_probe(
                command,
                cwd=probe_cwd,
                environment=environment,
                timeout_seconds=remaining,
            )
        except (OSError, subprocess.SubprocessError) as error:
            detail = (" ".join(str(error).split()) or type(error).__name__)[:2048]
            return DotnetReadinessFailure(
                stage,
                127,
                b"",
                (
                    "DevCoordinator could not start dotnet readiness "
                    f"({type(error).__name__}): {detail}\n"
                ).encode("utf-8", errors="replace"),
                global_json,
                sdk_version,
                False,
            )
        if completed.timed_out:
            stderr = completed.stderr + (
                "DevCoordinator dotnet readiness exhausted the caller's "
                f"{timeout_seconds}s execution timeout before project tests.\n"
            ).encode("utf-8")
            return DotnetReadinessFailure(
                stage,
                124,
                completed.stdout,
                stderr,
                global_json,
                sdk_version,
                False,
            )
        if completed.returncode != 0:
            combined = completed.stdout + b"\n" + completed.stderr
            unavailable = stage == "sdk" and (
                b"compatible .NET SDK was not found" in combined
                or b"Requested SDK version:" in combined
            )
            return DotnetReadinessFailure(
                stage,
                int(completed.returncode),
                completed.stdout,
                completed.stderr,
                global_json,
                sdk_version,
                unavailable,
            )
    return None


def _jsonl_cases(path: Path) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    if path.stat().st_size > MAX_REPORT_BYTES:
        raise TestStoreContractError("JSONL reporter output exceeds its bound")
    cases: list[dict[str, object]] = []
    failures: list[dict[str, object]] = []
    with path.open("r", encoding="utf-8", errors="strict") as stream:
        for index, line in enumerate(stream):
            if index >= MAX_CASES or len(line.encode("utf-8")) > 1024 * 1024:
                raise TestStoreContractError("JSONL reporter output is excessive")
            value = json.loads(line)
            if not isinstance(value, Mapping):
                raise TestStoreContractError("JSONL reporter event is invalid")
            raw_status = str(value.get("status") or value.get("outcome") or "")
            status = {
                "pass": "passed", "passed": "passed", "ok": "passed",
                "fail": "failed", "failed": "failed",
                "skip": "skipped", "skipped": "skipped",
                "error": "error",
            }.get(raw_status.lower())
            if status is None:
                continue
            case_id = str(value.get("case_id") or value.get("id") or f"case-{index}")[:1024]
            display = str(value.get("name") or value.get("display_name") or case_id)[:4096]
            duration = value.get("duration_seconds", value.get("duration", 0.0))
            if isinstance(duration, bool) or not isinstance(duration, (int, float)) or duration < 0:
                duration = 0.0
            case = {
                "case_id": case_id,
                "display_name": display,
                "status": status,
                "duration_seconds": float(duration),
                "location": None if value.get("location") is None else str(value["location"])[:4096],
            }
            cases.append(case)
            if status in {"failed", "error"}:
                failures.append(
                    {
                        "failure_id": "failure-" + hashlib.sha256(
                            f"{index}\0{case_id}".encode("utf-8")
                        ).hexdigest()[:32],
                        "classification": "test_failure",
                        "message": str(value.get("message") or display)[:8192],
                        "case_id": case_id,
                        "location": case["location"],
                        "artifact_id": None,
                    }
                )
    return cases, failures


def _trx_cases(path: Path) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    if path.stat().st_size > MAX_REPORT_BYTES:
        raise TestStoreContractError("TRX reporter output exceeds its bound")
    root = ET.parse(path).getroot()
    cases: list[dict[str, object]] = []
    failures: list[dict[str, object]] = []
    for index, element in enumerate(root.iter()):
        if index > MAX_CASES * 8:
            raise TestStoreContractError("TRX reporter output is excessive")
        if element.tag.rsplit("}", 1)[-1] != "UnitTestResult":
            continue
        outcome = str(element.attrib.get("outcome", "")).lower()
        status = {
            "passed": "passed", "failed": "failed", "notexecuted": "skipped",
            "inconclusive": "skipped", "error": "error",
        }.get(outcome, "error")
        case_id = str(element.attrib.get("testId") or f"trx-{len(cases)}")[:1024]
        display = str(element.attrib.get("testName") or case_id)[:4096]
        duration_text = str(element.attrib.get("duration") or "")
        duration = 0.0
        matched_duration = re.fullmatch(
            r"(?:(\d+)\.)?(\d+):(\d+):([0-9]+(?:\.[0-9]+)?)",
            duration_text,
        )
        if matched_duration is not None:
            days, hours, minutes, seconds = matched_duration.groups()
            duration = (
                int(days or 0) * 86_400
                + int(hours) * 3_600
                + int(minutes) * 60
                + float(seconds)
            )
        cases.append(
            {
                "case_id": case_id,
                "display_name": display,
                "status": status,
                "duration_seconds": duration,
                "location": None,
            }
        )
        if status in {"failed", "error"}:
            failures.append(
                {
                    "failure_id": "failure-" + hashlib.sha256(case_id.encode()).hexdigest()[:32],
                    "classification": "test_failure",
                    "message": display,
                    "case_id": case_id,
                    "location": None,
                    "artifact_id": None,
                }
            )
    return cases, failures


def _junit_cases(path: Path) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    if path.stat().st_size > MAX_REPORT_BYTES:
        raise TestStoreContractError("JUnit reporter output exceeds its bound")
    root = ET.parse(path).getroot()
    cases: list[dict[str, object]] = []
    failures: list[dict[str, object]] = []
    for element in root.iter():
        if element.tag.rsplit("}", 1)[-1] != "testcase":
            continue
        if len(cases) >= MAX_CASES:
            raise TestStoreContractError("JUnit reporter output is excessive")
        child_kinds = {child.tag.rsplit("}", 1)[-1] for child in element}
        status = (
            "error" if "error" in child_kinds else
            "failed" if "failure" in child_kinds else
            "skipped" if "skipped" in child_kinds else
            "passed"
        )
        display = str(element.attrib.get("name") or f"case-{len(cases)}")[:4096]
        classname = str(element.attrib.get("classname") or "")
        case_id = hashlib.sha256(
            f"{classname}\0{display}\0{len(cases)}".encode("utf-8")
        ).hexdigest()
        try:
            duration = max(0.0, float(element.attrib.get("time", "0")))
        except ValueError:
            duration = 0.0
        case = {
            "case_id": "case-" + case_id[:32],
            "display_name": display,
            "status": status,
            "duration_seconds": duration,
            "location": classname[:4096] or None,
        }
        cases.append(case)
        if status in {"failed", "error"} and len(failures) < MAX_FAILURES:
            detail = next(
                (
                    (child.text or child.attrib.get("message") or display)
                    for child in element
                    if child.tag.rsplit("}", 1)[-1] in {"failure", "error"}
                ),
                display,
            )
            failures.append(
                {
                    "failure_id": "failure-" + case_id[:32],
                    "classification": "test_failure",
                    "message": str(detail)[:8192],
                    "case_id": case["case_id"],
                    "location": case["location"],
                    "artifact_id": None,
                }
            )
    return cases, failures


def _result_chunks(
    descriptor: TestAttemptDescriptor,
    *,
    cases: Sequence[Mapping[str, object]],
    failures: Sequence[Mapping[str, object]],
    artifacts: Sequence[Mapping[str, object]],
    reporter_complete: bool,
) -> tuple[dict[str, object], ...]:
    """Partition reporter output into independently bounded store chunks."""

    limits = {"cases": 500, "failures": 64, "artifacts": 64}
    chunks: list[dict[str, object]] = []
    current: dict[str, object] = {
        "cases": [],
        "failures": [],
        "artifacts": [],
    }

    def encoded_size(value: Mapping[str, object]) -> int:
        probe = {
            "chunk_id": "chunk-" + "0" * 32,
            "chunk_index": len(chunks),
            "cases": value["cases"],
            "failures": value["failures"],
            "artifacts": value["artifacts"],
            "reporter_complete": False,
        }
        return len(_json_bytes(probe, maximum=MAX_RESULT_CHUNK_BYTES + 1))

    def flush() -> None:
        nonlocal current
        if not any(current[name] for name in ("cases", "failures", "artifacts")):
            return
        if len(chunks) >= MAX_RESULT_CHUNKS:
            raise TestStoreContractError("runner produced too many result chunks")
        chunks.append(current)
        current = {"cases": [], "failures": [], "artifacts": []}

    for field, values in (
        ("artifacts", artifacts),
        ("failures", failures),
        ("cases", cases),
    ):
        for raw in values:
            collection = current[field]
            if not isinstance(collection, list):
                raise TestStoreContractError("runner result chunk accumulator is invalid")
            collection.append(dict(raw))
            try:
                excessive = len(collection) > limits[field] or encoded_size(current) > MAX_RESULT_CHUNK_BYTES
            except TestStoreContractError:
                excessive = True
            if excessive:
                collection.pop()
                flush()
                replacement = current[field]
                if not isinstance(replacement, list):
                    raise TestStoreContractError(
                        "runner result chunk accumulator is invalid"
                    )
                replacement.append(dict(raw))
                if encoded_size(current) > MAX_RESULT_CHUNK_BYTES:
                    raise TestStoreContractError(
                        f"single runner {field[:-1]} exceeds the result chunk bound"
                    )
    flush()
    if not chunks:
        chunks.append({"cases": [], "failures": [], "artifacts": []})
    normalized: list[dict[str, object]] = []
    for index, values in enumerate(chunks):
        identity = hashlib.sha256(
            (
                descriptor.attempt_id
                + "\0"
                + str(descriptor.generation)
                + "\0"
                + str(index)
            ).encode("utf-8")
        ).hexdigest()[:32]
        normalized.append(
            {
                "chunk_id": "chunk-" + identity,
                "chunk_index": index,
                "cases": values["cases"],
                "failures": values["failures"],
                "artifacts": values["artifacts"],
                "reporter_complete": reporter_complete and index == len(chunks) - 1,
            }
        )
    return tuple(normalized)


def _write_result_chunks(
    output: Path, chunks: Sequence[Mapping[str, object]]
) -> list[dict[str, object]]:
    manifest: list[dict[str, object]] = []
    for index, chunk in enumerate(chunks):
        if chunk.get("chunk_index") != index:
            raise TestStoreContractError("runner result chunk ordering is invalid")
        payload = _json_bytes(chunk, maximum=MAX_RESULT_CHUNK_BYTES)
        name = f"result-chunk-{index:06d}.json"
        path = output / name
        descriptor_fd = os.open(
            path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        try:
            _write_all(descriptor_fd, payload)
            os.fsync(descriptor_fd)
        finally:
            os.close(descriptor_fd)
        manifest.append(
            {
                "chunk_id": chunk["chunk_id"],
                "chunk_index": index,
                "file_name": name,
                "sha256": hashlib.sha256(payload).hexdigest(),
                "size_bytes": len(payload),
                "reporter_complete": chunk["reporter_complete"],
            }
        )
    return manifest


def _terminal_outcome(
    *,
    returncode: int,
    incomplete_reporting: bool,
    failures: Sequence[Mapping[str, object]],
) -> str:
    """Classify trusted runner completion independently of process exit code."""

    classifications = {str(item.get("classification")) for item in failures}
    if incomplete_reporting:
        return "incomplete"
    if "timeout" in classifications:
        return "timed_out"
    if "infrastructure_failure" in classifications:
        return "infrastructure_failed"
    if "test_failure" in classifications or returncode != 0:
        return "test_failed"
    return "succeeded"


def run(
    descriptor: TestAttemptDescriptor, output: Path, result_path: Path
) -> int:
    global _EXACT_SECRET_VARIANTS
    _EXACT_SECRET_VARIANTS = _credential_secret_variants(descriptor)
    root = Path(descriptor.execution_root)
    cwd = (root / descriptor.cwd).resolve(strict=True)
    if root != cwd and root not in cwd.parents:
        raise TestStoreContractError("runner cwd escapes attempt root")
    stdout_path = output / f"{descriptor.attempt_id}-stdout.log"
    stderr_path = output / f"{descriptor.attempt_id}-stderr.log"
    for path in (stdout_path, stderr_path, result_path):
        path.unlink(missing_ok=True)
    adapted_argv, adapted_environment, generated_reporter, generated_kind = (
        adapt_driver_invocation(descriptor, output)
    )
    environment = {
        "PATH": "/usr/local/bin:/usr/bin:/bin",
        "HOME": str(output / "home"),
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        **adapted_environment,
    }
    # Some cross-platform tests need a short canonical scratch base (notably
    # for AF_UNIX) and cannot use the account database home hidden by the
    # native sandbox. Linux attempts receive a unit-private /tmp namespace;
    # test-created directories remain 0700 on other platforms.
    environment["DEVCOORDINATOR_TEST_TMP_ROOT"] = "/tmp"
    python_launch_executable = _immutable_python_launch_executable(descriptor)
    if python_launch_executable is not None:
        environment["PYTHONHOME"] = str(_IMMUTABLE_PYTHON_TOOLCHAIN_MOUNT)
    credential_directory = os.environ.get("CREDENTIALS_DIRECTORY")
    if descriptor.fixtures:
        if not credential_directory or not Path(credential_directory).is_absolute():
            raise TestStoreContractError("test fixture credentials are unavailable")
        environment["DEVCOORDINATOR_FIXTURE_DIRECTORY"] = credential_directory
        # Fixture consumers use the standard systemd credentials contract for
        # both the public fixture catalog and any broker-issued secret files.
        # The compatibility alias above remains for older harness adapters.
        environment["CREDENTIALS_DIRECTORY"] = credential_directory
    if descriptor.credentials:
        if not credential_directory or not Path(credential_directory).is_absolute():
            raise TestStoreContractError(
                "operational credential directory is unavailable"
            )
        environment["CREDENTIALS_DIRECTORY"] = credential_directory
    Path(environment["HOME"]).mkdir(mode=0o700, exist_ok=True)
    is_dotnet_invocation = _is_dotnet_project_invocation(descriptor)
    if is_dotnet_invocation:
        Path(environment["DOTNET_CLI_HOME"]).mkdir(mode=0o700, exist_ok=True)
    started = time.monotonic()
    deadline = started + descriptor.ttl_seconds
    usage_before = resource.getrusage(resource.RUSAGE_CHILDREN)
    stdout_state: dict[str, object] = {}
    stderr_state: dict[str, object] = {}
    launch_error: OSError | subprocess.SubprocessError | None = None
    readiness_failure: DotnetReadinessFailure | None = None
    project_execution_started = False
    project_timed_out = False
    try:
        readiness_failure = (
            _dotnet_readiness(
                adapted_argv,
                cwd=cwd,
                execution_root=root,
                environment=environment,
                timeout_seconds=descriptor.ttl_seconds,
                locked_restore=_dotnet_locked_restore_required(descriptor),
                output=output,
                deadline=deadline,
            )
            if is_dotnet_invocation
            else None
        )
        if readiness_failure is not None:
            returncode = readiness_failure.returncode
            _capture(io.BytesIO(readiness_failure.stdout), stdout_path, stdout_state)
            _capture(io.BytesIO(readiness_failure.stderr), stderr_path, stderr_state)
        else:
            process = subprocess.Popen(
                list(adapted_argv),
                executable=python_launch_executable,
                cwd=cwd,
                env=environment,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                start_new_session=True,
            )
            project_execution_started = True
            if process.stdout is None or process.stderr is None:
                process.kill()
                process.wait()
                raise TestStoreContractError("runner capture pipes are unavailable")
            threads = [
                threading.Thread(
                    target=_capture,
                    args=(process.stdout, stdout_path, stdout_state),
                ),
                threading.Thread(
                    target=_capture,
                    args=(process.stderr, stderr_path, stderr_state),
                ),
            ]
            for thread in threads:
                thread.start()
            remaining = deadline - time.monotonic()
            try:
                returncode = process.wait(timeout=max(0.0, remaining))
            except subprocess.TimeoutExpired:
                project_timed_out = True
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    process.kill()
                process.wait()
                returncode = 124
            else:
                try:
                    os.killpg(process.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            for thread in threads:
                thread.join()
            process.stdout.close()
            process.stderr.close()
    except (OSError, subprocess.SubprocessError) as error:
        launch_error = error
        returncode = 127
        detail = (" ".join(str(error).split()) or type(error).__name__)[:2048]
        _capture(io.BytesIO(b""), stdout_path, stdout_state)
        _capture(
            io.BytesIO(
                (
                    "DevCoordinator could not start the declared test process "
                    f"({type(error).__name__}): {detail}\n"
                ).encode("utf-8", errors="replace")
            ),
            stderr_path,
            stderr_state,
        )
    usage_after = resource.getrusage(resource.RUSAGE_CHILDREN)
    cpu_seconds = max(
        0.0,
        float(usage_after.ru_utime + usage_after.ru_stime)
        - float(usage_before.ru_utime + usage_before.ru_stime),
    )
    # Linux reports ru_maxrss in KiB. The runner has exactly one test child;
    # this provides durable best-effort evidence when systemd has already
    # collected the transient unit before the authority observes it.
    raw_peak_memory = int(usage_after.ru_maxrss)
    peak_memory_bytes = (
        raw_peak_memory * (1024 if sys.platform.startswith("linux") else 1)
        if raw_peak_memory > 0
        else None
    )
    _redact_capture_if_needed(stdout_path, stdout_state)
    _redact_capture_if_needed(stderr_path, stderr_state)
    secret_leak = bool(stdout_state.get("secret_redacted")) or bool(
        stderr_state.get("secret_redacted")
    )
    if secret_leak:
        returncode = 1
    duration = max(0.0, time.monotonic() - started)
    stdout_artifact = _capture_artifact(
        descriptor,
        stream_name="stdout",
        path=stdout_path,
        state=stdout_state,
    )
    stderr_artifact = _capture_artifact(
        descriptor,
        stream_name="stderr",
        path=stderr_path,
        state=stderr_state,
    )
    artifacts: list[Mapping[str, object]] = [stdout_artifact, stderr_artifact]
    reporter_path: Path | None = None
    # A trusted readiness/bootstrap result is itself complete evidence.  It did
    # not start the project reporter, so it must not be mislabeled as an
    # incomplete test report.
    incomplete = secret_leak or launch_error is not None
    failures: list[dict[str, object]] = []
    if launch_error is not None:
        failures.append(
            {
                "failure_id": "failure-" + hashlib.sha256(
                    (
                        descriptor.attempt_id
                        + "\0process-launch\0"
                        + type(launch_error).__name__
                        + "\0"
                        + (" ".join(str(launch_error).split())[:2048])
                    ).encode("utf-8")
                ).hexdigest()[:32],
                "classification": "infrastructure_failure",
                "message": (
                    "The declared test process could not be started "
                    f"({type(launch_error).__name__}); inspect the linked "
                    "bounded runner log"
                )[:8192],
                "case_id": None,
                "location": "runner/bootstrap",
                "artifact_id": stderr_artifact["artifact_id"],
            }
        )
    if readiness_failure is not None:
        evidence = (
            stderr_artifact
            if int(stderr_state.get("observed_bytes", 0)) > 0
            else stdout_artifact
        )
        global_json_label: str | None = None
        if readiness_failure.global_json is not None:
            try:
                global_json_label = readiness_failure.global_json.relative_to(
                    root
                ).as_posix()
            except ValueError:
                global_json_label = readiness_failure.global_json.name
        readiness_payload = (
            readiness_failure.stdout + b"\n" + readiness_failure.stderr
        ).upper()
        locked_graph_mismatch = (
            readiness_failure.stage == "restore"
            and (b"NU1004" in readiness_payload or b"NU1005" in readiness_payload)
        )
        if returncode == 124:
            classification = "timeout"
            message = (
                f"The trusted dotnet {readiness_failure.stage} timed out; "
                "inspect the linked bounded bootstrap log"
            )
        elif locked_graph_mismatch:
            classification = "test_failure"
            message = (
                "The project dependency graph does not match its locked restore "
                "contract; update the lock file and inspect the linked bounded log"
            )
        elif readiness_failure.sdk_unavailable:
            classification = "infrastructure_failure"
            subject = (
                f"The requested dotnet SDK {readiness_failure.sdk_version}"
                if readiness_failure.sdk_version is not None
                else "The requested dotnet SDK"
            )
            context = (
                f" from {global_json_label}"
                if global_json_label is not None
                else ""
            )
            message = (
                f"{subject}{context} is unavailable (exit status {returncode}); "
                "inspect the linked bounded SDK log"
            )
        elif readiness_failure.stage == "sdk":
            classification = "infrastructure_failure"
            message = (
                "The dotnet SDK failed selection/bootstrap readiness "
                f"(exit status {returncode}); inspect the linked bounded SDK log"
            )
        elif readiness_failure.stage == "restore":
            classification = "infrastructure_failure"
            message = (
                "The runner-owned offline locked dotnet restore failed "
                f"(exit status {returncode}); inspect the linked bounded bootstrap log"
            )
        else:
            classification = "infrastructure_failure"
            sdk_label = (
                f" for SDK {readiness_failure.sdk_version}"
                if readiness_failure.sdk_version is not None
                else ""
            )
            message = (
                f"The dotnet workload/bootstrap readiness{sdk_label} failed "
                f"(exit status {returncode}); inspect the linked bounded SDK log"
            )
        failures.append(
            {
                "failure_id": "failure-" + hashlib.sha256(
                    (
                        descriptor.attempt_id
                        + "\0dotnet-readiness\0"
                        + readiness_failure.stage
                        + "\0"
                        + str(returncode)
                    ).encode("utf-8")
                ).hexdigest()[:32],
                "classification": classification,
                "message": message[:8192],
                "case_id": None,
                "location": (
                    "setup/dotnet-lock"
                    if locked_graph_mismatch
                    else (
                        "runner/dotnet-bootstrap"
                        if readiness_failure.stage == "restore"
                        else "runner/dotnet-readiness"
                    )
                ),
                "artifact_id": evidence["artifact_id"],
            }
        )
    if project_timed_out:
        evidence = (
            stderr_artifact
            if int(stderr_state.get("observed_bytes", 0)) > 0
            else stdout_artifact
        )
        failures.append(
            {
                "failure_id": "failure-" + hashlib.sha256(
                    (descriptor.attempt_id + "\0project-timeout").encode("utf-8")
                ).hexdigest()[:32],
                "classification": "timeout",
                "message": (
                    "The declared test process exceeded the caller-selected "
                    f"{descriptor.ttl_seconds}s execution deadline; inspect "
                    "the linked bounded process log"
                ),
                "case_id": None,
                "location": "runner/execution",
                "artifact_id": evidence["artifact_id"],
            }
        )
    if secret_leak:
        failures.append(
            {
                "failure_id": "failure-" + uuid.uuid4().hex,
                "classification": "infrastructure_failure",
                "message": "test output contained protected credential material",
                "case_id": None,
                "location": None,
                "artifact_id": None,
            }
        )
    cases: list[dict[str, object]] = []
    if (
        launch_error is None
        and readiness_failure is None
        and not project_timed_out
    ):
        try:
            provenance_path = _write_execution_provenance(
                descriptor,
                output=output,
                cwd=cwd,
                argv=adapted_argv,
                environment=environment,
            )
            artifacts.append(
                _generated_artifact(
                    descriptor,
                    provenance_path,
                    kind="trace",
                    name="execution-provenance",
                )
            )
        except TestStoreContractError as error:
            incomplete = True
            failures.append(
                {
                    "failure_id": "failure-" + uuid.uuid4().hex,
                    "classification": "infrastructure_failure",
                    "message": str(error)[:8192],
                    "case_id": None,
                    "location": None,
                    "artifact_id": None,
                }
            )
    for policy in descriptor.artifacts:
        try:
            value = _artifact(descriptor, root, output, policy)
            if value is not None:
                artifacts.append(value)
                if (
                    reporter_path is None
                    and policy["kind"] in {"jsonl", "trx", "junit"}
                ):
                    reporter_path = Path(str(value["_source_path"]))
        except TestStoreContractError as error:
            incomplete = True
            failures.append(
                {
                    "failure_id": "failure-" + uuid.uuid4().hex,
                    "classification": "incomplete_reporting",
                    "message": str(error)[:8192],
                    "case_id": None,
                    "location": None,
                    "artifact_id": None,
                }
            )
    failure_diagnostic_artifact: Mapping[str, object] | None = None
    if returncode != 0 and launch_error is None and not project_timed_out:
        failure_diagnostic_artifact = _directory_failure_diagnostic(
            descriptor,
            artifacts,
            output=output,
        )
        if failure_diagnostic_artifact is not None:
            artifacts.append(failure_diagnostic_artifact)
    if len(artifacts) > MAX_ARTIFACTS:
        incomplete = True
        artifacts = artifacts[:MAX_ARTIFACTS]
    if generated_reporter.exists():
        try:
            generated = _generated_artifact(
                descriptor,
                generated_reporter,
                kind=generated_kind,
                name="coordinator-reporter",
            )
            artifacts.append(generated)
            reporter_path = generated_reporter
        except TestStoreContractError as error:
            incomplete = True
            failures.append(
                {
                    "failure_id": "failure-" + uuid.uuid4().hex,
                    "classification": "incomplete_reporting",
                    "message": str(error)[:8192],
                    "case_id": None,
                    "location": None,
                    "artifact_id": None,
                }
            )
    elif (
        descriptor.driver == "automation"
        and launch_error is None
        and not project_timed_out
    ):
        # Automation adapters may wrap compound repository checks.  Preserve
        # one explicit target-level case when the script has no case stream;
        # other typed drivers must publish their injected reporter.
        cases = [
            {
                "case_id": "case-" + hashlib.sha256(
                    descriptor.attempt_id.encode("utf-8")
                ).hexdigest()[:32],
                "display_name": descriptor.target_name,
                "status": "passed" if returncode == 0 else "failed",
                "duration_seconds": duration,
                "location": None,
            }
        ]
    elif (
        launch_error is None
        and readiness_failure is None
        and not project_timed_out
    ):
        incomplete = True
        failures.append(
            {
                "failure_id": "failure-" + uuid.uuid4().hex,
                "classification": "incomplete_reporting",
                "message": f"{descriptor.driver} reporter output was not produced",
                "case_id": None,
                "location": None,
                "artifact_id": None,
            }
        )
    if reporter_path is not None:
        try:
            if generated_kind == "trx" or descriptor.reporter == "trx":
                cases, reporter_failures = _trx_cases(reporter_path)
            elif generated_kind == "junit":
                cases, reporter_failures = _junit_cases(reporter_path)
            else:
                cases, reporter_failures = _jsonl_cases(reporter_path)
            failures.extend(reporter_failures)
        except Exception as error:
            incomplete = True
            failures.append(
                {
                    "failure_id": "failure-" + uuid.uuid4().hex,
                    "classification": "incomplete_reporting",
                    "message": f"reporter output is invalid: {type(error).__name__}",
                    "case_id": None,
                    "location": None,
                    "artifact_id": None,
                }
            )
    if (
        project_execution_started
        and not project_timed_out
        and returncode != 0
        and not any(
            failure["classification"] == "test_failure" for failure in failures
        )
    ):
        # A process exit is still actionable even when an automation reporter
        # produced no failing case (or failed before it could do so).  Link the
        # concise failure to bounded evidence without copying arbitrary project
        # output into the agent summary.
        evidence = failure_diagnostic_artifact or (
            stderr_artifact
            if int(stderr_state.get("observed_bytes", 0)) > 0
            else stdout_artifact
        )
        failures.append(
            {
                "failure_id": "failure-" + hashlib.sha256(
                    (
                        descriptor.attempt_id
                        + "\0process-exit\0"
                        + str(returncode)
                    ).encode("utf-8")
                ).hexdigest()[:32],
                "classification": "test_failure",
                "message": (
                    f"{descriptor.target_name} exited with status {returncode}; "
                    "inspect the linked bounded process log"
                )[:8192],
                "case_id": None,
                "location": None,
                "artifact_id": evidence["artifact_id"],
            }
        )
    failures = failures[:MAX_FAILURES]
    artifacts = artifacts[:MAX_ARTIFACTS]
    artifacts, artifact_sources = _artifact_sources(
        artifacts,
        output=output,
        execution_root=root,
    )
    chunks = _result_chunks(
        descriptor,
        cases=cases,
        failures=failures,
        artifacts=artifacts,
        reporter_complete=not incomplete,
    )
    chunk_manifest = _write_result_chunks(output, chunks)
    public_stdout_state = {
        key: value for key, value in stdout_state.items() if not key.startswith("_")
    }
    public_stderr_state = {
        key: value for key, value in stderr_state.items() if not key.startswith("_")
    }
    for state in (stdout_state, stderr_state):
        descriptor_fd = state.pop("_descriptor", None)
        if type(descriptor_fd) is int:
            os.close(descriptor_fd)
    terminal_outcome = _terminal_outcome(
        returncode=returncode,
        incomplete_reporting=incomplete,
        failures=failures,
    )
    result = {
        "schema_version": 3,
        "attempt_id": descriptor.attempt_id,
        "generation": descriptor.generation,
        "returncode": returncode,
        "duration_seconds": duration,
        "peak_memory_bytes": peak_memory_bytes,
        "cpu_seconds": cpu_seconds,
        "incomplete_reporting": incomplete,
        "terminal_outcome": terminal_outcome,
        "captures": {
            "stdout": {
                "path": str(stdout_path),
                "artifact_id": stdout_artifact["artifact_id"],
                **public_stdout_state,
            },
            "stderr": {
                "path": str(stderr_path),
                "artifact_id": stderr_artifact["artifact_id"],
                **public_stderr_state,
            },
        },
        "artifact_sources": artifact_sources,
        "chunk_manifest": chunk_manifest,
    }
    payload = _json_bytes(result)
    descriptor_fd = os.open(
        result_path,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        _write_all(descriptor_fd, payload)
        os.fsync(descriptor_fd)
    finally:
        os.close(descriptor_fd)
    return 0 if returncode == 0 and not incomplete else 1


def _json_bytes(value: object, *, maximum: int = MAX_RESULT_BYTES) -> bytes:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
    ).encode("utf-8")
    if len(payload) > maximum:
        raise TestStoreContractError("runner result exceeds its bound")
    return payload


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="devcoordinator-test-runner")
    parser.add_argument("--launch", type=Path, required=True)
    arguments = parser.parse_args(argv)
    descriptor, output_root, result_path = _load(arguments.launch)
    return run(descriptor, output_root, result_path)


if __name__ == "__main__":
    raise SystemExit(main())
